name: flask-app
type: python:3.10
build:
  flavor: none

dependencies:
  python:
    pip: ">=23.0"

web:
  commands:
    start: python app.py
  locations:
    "/":
      root: ""
      passthru: false
      scripts: true

mounts:
  "/data":
    source: local
    source_path: data

relationships:
  solr: "solr:solr"

disk: 512

hooks:
  build: |
    pip install -r requirements.txt
  deploy: |
    # Create Solr core 'mycore' if it doesn't exist
    curl -s "http://solr.internal:8080/solr/admin/cores?action=STATUS&core=mycore" | grep -q '"mycore"' || \
    curl "http://solr.internal:8080/solr/admin/cores?action=CREATE&name=mycore&instanceDir=mycore"
