name: flask-app
type: "python:3.10"

dependencies:
  python:
    flask: "*"
    requests: "*"

web:
  commands:
    start: python app.py
  locations:
    "/":
      root: ""
      passthru: false
      scripts: true

mounts:
  "/data":
    source: local
    source_path: data

relationships:
  solr: "solr:solr"

disk: 512

hooks:
  build: |
    pip install -r requirements.txt
  deploy: |
    echo "Checking Solr core..."
    curl -s "http://solr.internal:8080/solr/admin/cores?action=STATUS&core=mycore" | grep -q '"mycore"' || \
    curl "http://solr.internal:8080/solr/admin/cores?action=CREATE&name=mycore&instanceDir=mycore"
