name: Deploy to Platform.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Platform.sh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php
          mkdir -p ~/.platformsh/bin
          mv platform.phar ~/.platformsh/bin/platform
          chmod +x ~/.platformsh/bin/platform

      - name: Add Platform.sh CLI to PATH
        run: echo "$HOME/.platformsh/bin" >> $GITHUB_PATH

      - name: Authenticate Platform.sh
        run: platform auth:api-token ${{ secrets.PLATFORM_API_TOKEN }}
        env:
          PLATFORM_API_TOKEN: ${{ secrets.PLATFORM_API_TOKEN }}

      - name: Push to Platform.sh
        run: platform push --yes
