name: Deploy to Platform.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Prevent shallow clone error

      - name: Install Platform.sh CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
          echo "$HOME/.platformsh/bin" >> $GITHUB_PATH

      - name: Deploy to Platform.sh
        run: |
          platform push --yes --project=hiaxa77qsgape --force
