name: Deploy to Platform.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORM_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Platform.sh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php
          echo "$HOME/.platformsh/bin" >> $GITHUB_PATH

      - name: Deploy to Platform.sh
        run: ~/.platformsh/bin/platform push --yes
