name: Deploy to Platform.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Platform.sh CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | bash
          echo "$HOME/.platformsh/bin" >> $GITHUB_PATH

      - name: Configure auth token for Platform.sh CLI
        run: |
          mkdir -p ~/.platformsh
          echo "{\"api_token\": \"${{ secrets.PLATFORMSH_CLI_TOKEN }}\"}" > ~/.platformsh/config.json

      - name: Deploy to Platform.sh
        run: platform push --yes --project=hiaxa77qsgape
