name: Deploy to Platform.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Platform.sh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php
          echo "$HOME/.platformsh/bin" >> $GITHUB_PATH

      - name: Authenticate using API token
        run: |
          echo "$PLATFORM_API_TOKEN" | ~/.platformsh/bin/platform auth:api-token-login --no-interaction
        env:
          PLATFORM_API_TOKEN: ${{ secrets.PLATFORM_API_TOKEN }}

      - name: Push to Platform.sh
        run: ~/.platformsh/bin/platform push --yes
